version: "3.7"

services:
  web:
    image: crazymax/rtorrent-rutorrent:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 6881:6881/udp
      - 8000:8000
      - 8080:8080
      - 9000:9000
      - 50000:50000
    env_file:
      - rutorrent.env_file
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/downloads:/downloads
      - ${APP_DATA_DIR}/passwd:/passwd
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
