version: "3.7"

services:
  web:
    image: crazymax/rtorrent-rutorrent:latest
    restart: on-failure
    stop_grace_period: 1m
    expose:
      - ${RT_DHT_PORT}/udp
      - ${XMLRPC_PORT}
      - ${RUTORRENT_PORT}
      - ${WEBDAV_PORT}
      - ${RT_INC_PORT}
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - rutorrent.env_file
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/downloads:/downloads
      - ${APP_DATA_DIR}/passwd:/passwd
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
